version: "3.0"

services:
  redis:
    container_name: "Origami.Redis"
    image: redis:6.2-alpine
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password --user user
  redis_admin:
    container_name: "Origami.RedisAdmin"
    image: erikdubbelboer/phpredisadmin
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: "Origami.RedisAdmin"
      REDIS_1_PORT: 6379
      REDIS_1_AUTH: "password"
    ports:
      - "6381:80"
